apiVersion: v1
kind: Service
metadata:
  name: hello-world-clusterip
spec:
  selector:
    app: hello-world-clusterip
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
